# Start from Golang base image
FROM golang:1.24

# Set working directory
WORKDIR /app

# Install ffmpeg and curl (for downloading yt-dlp)
RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Download yt-dlp binary directly (no pip)
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
    -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp

# Copy Go source code
COPY . .

# Build Go binary
RUN go build -o server .

# Expose app port
EXPOSE 8000

# Run app
CMD ["./server"]
